// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ProjectAssetBind(arg1) {
  return window['go']['main']['App']['ProjectAssetBind'](arg1);
}

export function ProjectAssetBindingUnlock(arg1) {
  return window['go']['main']['App']['ProjectAssetBindingUnlock'](arg1);
}

export function ProjectAssetBindingsList(arg1) {
  return window['go']['main']['App']['ProjectAssetBindingsList'](arg1);
}

export function ProjectAssetImport(arg1) {
  return window['go']['main']['App']['ProjectAssetImport'](arg1);
}

export function ProjectAssetsList(arg1) {
  return window['go']['main']['App']['ProjectAssetsList'](arg1);
}

export function ProjectContinuityList(arg1) {
  return window['go']['main']['App']['ProjectContinuityList'](arg1);
}

export function ProjectContinuityRuleSave(arg1) {
  return window['go']['main']['App']['ProjectContinuityRuleSave'](arg1);
}

export function ProjectContinuityRuleUnlock(arg1) {
  return window['go']['main']['App']['ProjectContinuityRuleUnlock'](arg1);
}

export function ProjectCreate(arg1) {
  return window['go']['main']['App']['ProjectCreate'](arg1);
}

export function ProjectGenerationPackageExport(arg1) {
  return window['go']['main']['App']['ProjectGenerationPackageExport'](arg1);
}

export function ProjectGraphLayoutSave(arg1) {
  return window['go']['main']['App']['ProjectGraphLayoutSave'](arg1);
}

export function ProjectGraphView(arg1) {
  return window['go']['main']['App']['ProjectGraphView'](arg1);
}

export function ProjectHealth(arg1) {
  return window['go']['main']['App']['ProjectHealth'](arg1);
}

export function ProjectMainReferenceSet(arg1) {
  return window['go']['main']['App']['ProjectMainReferenceSet'](arg1);
}

export function ProjectMockRunCancel(arg1) {
  return window['go']['main']['App']['ProjectMockRunCancel'](arg1);
}

export function ProjectMockRunRetry(arg1) {
  return window['go']['main']['App']['ProjectMockRunRetry'](arg1);
}

export function ProjectMockRunStart(arg1) {
  return window['go']['main']['App']['ProjectMockRunStart'](arg1);
}

export function ProjectOpen(arg1) {
  return window['go']['main']['App']['ProjectOpen'](arg1);
}

export function ProjectSave(arg1) {
  return window['go']['main']['App']['ProjectSave'](arg1);
}

export function ProjectScriptDocumentLoad(arg1) {
  return window['go']['main']['App']['ProjectScriptDocumentLoad'](arg1);
}

export function ProjectScriptDocumentSave(arg1) {
  return window['go']['main']['App']['ProjectScriptDocumentSave'](arg1);
}

export function ProjectScriptSceneConfirm(arg1) {
  return window['go']['main']['App']['ProjectScriptSceneConfirm'](arg1);
}

export function ProjectShotCandidateConfirm(arg1) {
  return window['go']['main']['App']['ProjectShotCandidateConfirm'](arg1);
}

export function ProjectShotCandidateReject(arg1) {
  return window['go']['main']['App']['ProjectShotCandidateReject'](arg1);
}

export function ProjectShotCandidateSave(arg1) {
  return window['go']['main']['App']['ProjectShotCandidateSave'](arg1);
}

export function ProjectShotCandidatesList(arg1) {
  return window['go']['main']['App']['ProjectShotCandidatesList'](arg1);
}

export function ProjectShotContextMarkDirty(arg1) {
  return window['go']['main']['App']['ProjectShotContextMarkDirty'](arg1);
}

export function ProjectShotContextPromote(arg1) {
  return window['go']['main']['App']['ProjectShotContextPromote'](arg1);
}

export function ProjectShotContextValidate(arg1) {
  return window['go']['main']['App']['ProjectShotContextValidate'](arg1);
}

export function ShellHealth() {
  return window['go']['main']['App']['ShellHealth']();
}

export function WorkbenchProbe(arg1) {
  return window['go']['main']['App']['WorkbenchProbe'](arg1);
}
