// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';
import {project} from '../models';

export function AppInfo():Promise<shell.Info>;

export function ProjectAssetBind(arg1:project.BindAssetCommand):Promise<project.ContinuityLibraryResult>;

export function ProjectAssetBindingUnlock(arg1:project.UnlockAssetBindingCommand):Promise<project.ContinuityResult>;

export function ProjectAssetBindingsList(arg1:project.ListAssetBindingsCommand):Promise<project.ContinuityLibraryResult>;

export function ProjectAssetImport(arg1:project.ImportAssetCommand):Promise<project.AssetLibraryResult>;

export function ProjectAssetsList(arg1:project.ListAssetsCommand):Promise<project.AssetLibraryResult>;

export function ProjectContinuityList(arg1:project.ListContinuityCommand):Promise<project.ContinuityResult>;

export function ProjectContinuityRuleSave(arg1:project.SaveContinuityRuleCommand):Promise<project.ContinuityResult>;

export function ProjectContinuityRuleUnlock(arg1:project.UnlockContinuityRuleCommand):Promise<project.ContinuityResult>;

export function ProjectCreate(arg1:project.CreateProjectCommand):Promise<project.OperationResult>;

export function ProjectGenerationPackageExport(arg1:project.ExportGenerationPackageCommand):Promise<project.GenerationPackageResult>;

export function ProjectGraphLayoutSave(arg1:project.SaveGraphLayoutCommand):Promise<project.GraphViewResult>;

export function ProjectGraphView(arg1:project.GraphViewCommand):Promise<project.GraphViewResult>;

export function ProjectHealth(arg1:project.CheckProjectHealthCommand):Promise<project.OperationResult>;

export function ProjectMainReferenceSet(arg1:project.SetMainReferenceCommand):Promise<project.ContinuityLibraryResult>;

export function ProjectMockRunCancel(arg1:project.MockRunCommand):Promise<project.MockRunResult>;

export function ProjectMockRunRetry(arg1:project.MockRunCommand):Promise<project.MockRunResult>;

export function ProjectMockRunStart(arg1:project.MockRunCommand):Promise<project.MockRunResult>;

export function ProjectOpen(arg1:project.OpenProjectCommand):Promise<project.OperationResult>;

export function ProjectSave(arg1:project.SaveProjectCommand):Promise<project.OperationResult>;

export function ProjectScriptDocumentLoad(arg1:project.LoadScriptDocumentCommand):Promise<project.ScriptDocumentResult>;

export function ProjectScriptDocumentSave(arg1:project.SaveScriptDocumentCommand):Promise<project.ScriptDocumentResult>;

export function ProjectScriptSceneConfirm(arg1:project.ConfirmScriptSceneCommand):Promise<project.ScriptSceneCandidateResult>;

export function ProjectShotCandidateConfirm(arg1:project.ConfirmShotCandidateCommand):Promise<project.ScriptSceneCandidateResult>;

export function ProjectShotCandidateReject(arg1:project.RejectShotCandidateCommand):Promise<project.ScriptSceneCandidateResult>;

export function ProjectShotCandidateSave(arg1:project.SaveShotCandidateCommand):Promise<project.ScriptSceneCandidateResult>;

export function ProjectShotCandidatesList(arg1:project.ListShotCandidatesCommand):Promise<project.ScriptSceneCandidateResult>;

export function ProjectShotContextMarkDirty(arg1:project.MarkShotContextDirtyCommand):Promise<project.ShotContextResult>;

export function ProjectShotContextPromote(arg1:project.PromoteShotContextCommand):Promise<project.ShotContextResult>;

export function ProjectShotContextValidate(arg1:project.ValidateShotContextCommand):Promise<project.ShotContextResult>;

export function ShellHealth():Promise<shell.Health>;

export function WorkbenchProbe(arg1:shell.WorkbenchProbeCommand):Promise<shell.WorkbenchProbeResult>;
