// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ShellHealth() {
  return window['go']['main']['App']['ShellHealth']();
}

export function WorkbenchProbe(arg1) {
  return window['go']['main']['App']['WorkbenchProbe'](arg1);
}
