// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';

export function AppInfo():Promise<shell.Info>;

export function ShellHealth():Promise<shell.Health>;
