// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {shell} from '../models';
import {project} from '../models';

export function AppInfo():Promise<shell.Info>;

export function ProjectCreate(arg1:project.CreateProjectCommand):Promise<project.OperationResult>;

export function ProjectGraphView(arg1:project.GraphViewCommand):Promise<project.GraphViewResult>;

export function ProjectHealth(arg1:project.CheckProjectHealthCommand):Promise<project.OperationResult>;

export function ProjectOpen(arg1:project.OpenProjectCommand):Promise<project.OperationResult>;

export function ProjectSave(arg1:project.SaveProjectCommand):Promise<project.OperationResult>;

export function ShellHealth():Promise<shell.Health>;

export function WorkbenchProbe(arg1:shell.WorkbenchProbeCommand):Promise<shell.WorkbenchProbeResult>;
