// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ProjectCreate(arg1) {
  return window['go']['main']['App']['ProjectCreate'](arg1);
}

export function ProjectHealth(arg1) {
  return window['go']['main']['App']['ProjectHealth'](arg1);
}

export function ProjectOpen(arg1) {
  return window['go']['main']['App']['ProjectOpen'](arg1);
}

export function ProjectSave(arg1) {
  return window['go']['main']['App']['ProjectSave'](arg1);
}

export function ShellHealth() {
  return window['go']['main']['App']['ShellHealth']();
}

export function WorkbenchProbe(arg1) {
  return window['go']['main']['App']['WorkbenchProbe'](arg1);
}
